# Site settings
title: "Andrew's blog."
email: asturges@gmail.com
description: > # this means to ignore newlines until "baseurl:"
    Andrew Sturges. Blog. Hi.
baseurl: "/blog" # the subpath of your site, e.g. /blog/
url: "http://andrewsturges.com" # the base hostname & protocol for your site
twitter_username: andrewsturges
github_username:  arsturges

# Build settings
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
#pygments: true
